services:
  - type: web
    name: ladybug-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: ladybug-api
          property: port
    healthCheckPath: /health
    autoDeploy: true
